# Generated by Django 5.1.7 on 2025-06-17 04:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JenisBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jenis Barang',
                'verbose_name_plural': 'Jenis Barang',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('gambar', models.ImageField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis_barang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.jenisbarang')),
            ],
            options={
                'verbose_name': 'Barang',
                'verbose_name_plural': 'Barang',
                'ordering': ['nama', 'jenis_barang'],
            },
        ),
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lantai', models.IntegerField()),
                ('ruangan', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lokasi',
                'verbose_name_plural': 'Lokasi',
                'ordering': ['lantai', 'ruangan'],
                'unique_together': {('lantai', 'ruangan')},
            },
        ),
        migrations.CreateModel(
            name='Inventaris',
            fields=[
                ('kode_inventaris', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('kondisi', models.CharField(choices=[('baik', 'Baik'), ('rusak', 'Rusak'), ('hilang', 'Hilang')], default='baik', max_length=10)),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.barang')),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.lokasi')),
            ],
            options={
                'verbose_name': 'Inventaris',
                'verbose_name_plural': 'Inventaris',
                'ordering': ['barang__nama', 'lokasi__lantai', 'lokasi__ruangan'],
            },
        ),
        migrations.CreateModel(
            name='Pemindahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.TextField(blank=True)),
                ('tanggal_pemindahan', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pemindahan',
                'verbose_name_plural': 'Pemindahan',
                'ordering': ['-created_at', '-tanggal_pemindahan'],
            },
        ),
        migrations.CreateModel(
            name='PemindahanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventaris', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.inventaris')),
                ('lokasi_awal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemindahan_awal', to='catalog.lokasi')),
                ('lokasi_tujuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemindahan_tujuan', to='catalog.lokasi')),
                ('pemindahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.pemindahan')),
            ],
            options={
                'verbose_name': 'Detail Pemindahan',
                'verbose_name_plural': 'Detail Pemindahan',
                'ordering': ['pemindahan', 'inventaris__barang__nama'],
            },
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('pengembalian_diajukan', 'Pengembalian Diajukan'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('peminjaman_dibatalkan', 'Peminjaman Dibatalkan')], default='pending', max_length=50)),
                ('catatan_staff', models.TextField(blank=True)),
                ('keterangan', models.TextField()),
                ('tanggal_pinjam', models.DateField(default=django.utils.timezone.now)),
                ('tanggal_kembali', models.DateField(blank=True, null=True)),
                ('tanggal_dikembalikan', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Peminjaman',
                'verbose_name_plural': 'Peminjaman',
                'ordering': ['-created_at', '-tanggal_pinjam'],
            },
        ),
        migrations.CreateModel(
            name='PeminjamanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.barang')),
                ('peminjaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.peminjaman')),
            ],
            options={
                'verbose_name': 'Detail Peminjaman',
                'verbose_name_plural': 'Detail Peminjaman',
                'ordering': ['peminjaman', 'barang__nama'],
            },
        ),
        migrations.CreateModel(
            name='PeminjamanUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kondisi_pinjam', models.CharField(max_length=100)),
                ('kondisi_kembali', models.CharField(blank=True, max_length=100, null=True)),
                ('inventaris', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.inventaris')),
                ('peminjaman_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.peminjamandetail')),
            ],
            options={
                'ordering': ['inventaris__barang__nama'],
            },
        ),
    ]
